//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneForm {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoneForm.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string aceptar {
            get {
                return ResourceManager.GetString("aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A&amp;cerca de....
        /// </summary>
        public static string acercaDe {
            get {
                return ResourceManager.GetString("acercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Archivo.
        /// </summary>
        public static string archivo {
            get {
                return ResourceManager.GetString("archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Borrar.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        public static string conf {
            get {
                return ResourceManager.GetString("conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que quieres salir?.
        /// </summary>
        public static string confSalir {
            get {
                return ResourceManager.GetString("confSalir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar número.
        /// </summary>
        public static string errorGuardar {
            get {
                return ResourceManager.GetString("errorGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Guardar.
        /// </summary>
        public static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono normalillo, que no obedece a su principal función, llamar, pero que permite guardar números, SÓLO números :D.
        /// </summary>
        public static string infoApp {
            get {
                return ResourceManager.GetString("infoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intentos restantes:.
        /// </summary>
        public static string intentos {
            get {
                return ResourceManager.GetString("intentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tienes que introducir un número.
        /// </summary>
        public static string introduceNum {
            get {
                return ResourceManager.GetString("introduceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduce PIN.
        /// </summary>
        public static string introPIN {
            get {
                return ResourceManager.GetString("introPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  Longitud 4 dígitos. .
        /// </summary>
        public static string longPin {
            get {
                return ResourceManager.GetString("longPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El PIN tiene que ser un número..
        /// </summary>
        public static string numPin {
            get {
                return ResourceManager.GetString("numPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PIN no válido..
        /// </summary>
        public static string pinNoValido {
            get {
                return ResourceManager.GetString("pinNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &amp;Salir.
        /// </summary>
        public static string salir {
            get {
                return ResourceManager.GetString("salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono ring ring.
        /// </summary>
        public static string tituloForm {
            get {
                return ResourceManager.GetString("tituloForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los archivos.
        /// </summary>
        public static string todosArchivos {
            get {
                return ResourceManager.GetString("todosArchivos", resourceCulture);
            }
        }
    }
}
